---
apiVersion: v1
kind: Pod
metadata:
  name: qamanager-{{ .Values.service.instance.id }}
  labels:
    role: qamanager
    run: qamanager-{{ .Values.service.instance.id }}
spec:
  containers:
        - name: sandbox-health
          image: 882757728917.dkr.ecr.us-west-2.amazonaws.com/grplife-node:latest
          ports:
          - containerPort: 3002
          env:
            - name: SANDBOX_LABEL
              value: {{ .Values.service.instance.id }}
            - name: SANDBOX_VERIFICATION
              value: '{{ .Values.service.instance.verification }}'
            - name: SANDBOX_TIMESTAMP
              value: {{ now | date "2006-01-02T15:04:05" }}
        - name: redis
          image: redis:alpine
          ports:
          - containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
          - mountPath: /data
            name: redis-data
          resources:
            limits:
              memory: 128Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 128Mi
        - name: mysql-sandbox
          image: 882757728917.dkr.ecr.us-west-2.amazonaws.com/grplife-sandbox-mysql:{{ .Values.service.version.mysql }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sandbox-secrets
                  key: root.password
            - name: GITLAB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-secrets
                  key: git.access.token
            - name: AWS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-security
                  key: aws.access.key.id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-security
                  key: aws.secret.access.key
            - name: SANDBOX_LABEL
              value: {{ .Values.service.instance.id }}
            - name: SANDBOX_USER
              value: {{ .Values.service.instance.user }}
            - name: SBOX_DB_BACKUP_FILE
              value: {{ .Values.service.mysql.datafile }}
        - name: grplife-sandbox-{{ .Values.service.instance.id }}
          image: 882757728917.dkr.ecr.us-west-2.amazonaws.com/grplife-sandbox:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /tomcat-data
              name: tomcat-data
            - name: mysql-sandbox-init-scripts
              mountPath: /etc/scripts
            - name: tz-config
              mountPath: /etc/localtime
            - name: carmelsuite-config
              mountPath: /etc/carmel/carmelsuite_properties
            - name: carmelsuite-creds
              mountPath: /etc/carmel/carmelsuite_creds_properties
          env:
            - name: region
              value: {{ .Values.service.runregion }}
            - name: AWS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-security
                  key: aws.access.key.id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-security
                  key: aws.secret.access.key
            - name: aws.access.key.id
              valueFrom:
                secretKeyRef:
                  name: aws-security
                  key: aws.access.key.id
            - name: aws.secret.access.key
              valueFrom:
                secretKeyRef:
                  name: aws-security
                  key: aws.secret.access.key
            - name: aws.s3.bucket
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: aws.s3.bucket
            - name: aws.s3.path
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: aws.s3.path
            - name: aws.s3.region
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: aws.s3.region
            - name: twilio.api.mp3.uri
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: twilio.api.mp3.uri
            - name: twilio.api.recording.callback.uri
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: twilio.api.recording.callback.uri
            - name: twilio.api.phonetree.xml
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: twilio.api.phonetree.xml
            - name: twilio.api.phonetree.end.xml
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: twilio.api.phonetree.end.xml
            - name: twilio.account.default.phone
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: twilio.account.default.phone
            - name: intercom.apikey
              valueFrom:
                secretKeyRef:
                  name: intercom-security
                  key: intercom.apikey
            - name: GITLAB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-secrets
                  key: gitlab.api.key
            - name: JDBC_URL_READ
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: jdbc.url.read
            - name: JDBC_URL_READWRITE
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: jdbc.url.readwrite
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grplife-secrets
                  key: jdbc.username
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grplife-secrets
                  key: jdbc.password
            - name: twilio.account.auth.token
              valueFrom:
                secretKeyRef:
                  name: twilio-security
                  key: account.auth.token
            - name: twilio.account.sid
              valueFrom:
                secretKeyRef:
                  name: twilio-security
                  key: account.sid
            - name: redis.cache.server
              value: '127.0.0.1'
            - name: SANDBOX_USER
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: sandbox.user
            - name: SANDBOX_LABEL
              valueFrom:
                configMapKeyRef:
                  name: grplife-sandbox-{{ .Values.service.instance.id }}-config
                  key: sandbox.label
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: redis-data
    emptyDir: {}
  - name: tomcat-data
    emptyDir: {}
  - name: mysql-sandbox-init-scripts
    configMap:
      name: mysql-sandbox-{{ .Values.service.instance.id }}-scripts
  - name: tz-config
    hostPath:
      path: /usr/share/zoneinfo/America/Los_Angeles
  - name: carmelsuite-config
    projected:
      sources:
      - configMap:
          name: grplife-sandbox-{{ .Values.service.instance.id }}-config
  - name: carmelsuite-creds
    projected:
      sources:
      - secret:
          name: twilio-security
      - secret:
          name: mail-api
      - secret:
          name: grplife-secrets