---
apiVersion: v1
kind: Service
metadata:
   name: qamanager-{{ .Values.service.region }}
   labels:
     run: qamanager-{{ .Values.service.region }}
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    run: qamanager-{{ .Values.service.region }}