server:
  port : 8081

logging:
  level:
    org:
      hibernate:
        SQL: WARN

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      format_sql: true
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

---

spring:
  profiles: dev
  datasource:
    url: 'jdbc:postgresql://localhost:5432/qamanager'
    #username: qamanager
    #password: qa_manag3r1
    username: postgres
    password: password

---

spring:
  profiles: prod
  datasource:
    url: 'jdbc:postgresql://localhost:5432/qamanager'
    username: qamanager
    password: qa_manag3r1